// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFG_kFFLeJXSKTz6LKCwyitCGBI5pLNM',
    appId: '1:725686010307:web:fc5fc821ff20f44e0cfd76',
    messagingSenderId: '725686010307',
    projectId: 'satoshi-airline',
    authDomain: 'satoshi-airline.firebaseapp.com',
    storageBucket: 'satoshi-airline.appspot.com',
    measurementId: 'G-FKQ01V8MX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhY-cP86H0XUDyNxXkbtSMxglb2xKc65o',
    appId: '1:725686010307:android:1c4bba444de482800cfd76',
    messagingSenderId: '725686010307',
    projectId: 'satoshi-airline',
    storageBucket: 'satoshi-airline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmPqljXEMz_qqLvzLvWEEWoug5osPO78k',
    appId: '1:725686010307:ios:fc4e04fec180d3850cfd76',
    messagingSenderId: '725686010307',
    projectId: 'satoshi-airline',
    storageBucket: 'satoshi-airline.appspot.com',
    iosClientId: '725686010307-d282n2qsfi90qskro5s4qdsipfkqdddp.apps.googleusercontent.com',
    iosBundleId: 'satoshiairline.apples.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmPqljXEMz_qqLvzLvWEEWoug5osPO78k',
    appId: '1:725686010307:ios:af3d4228726114b00cfd76',
    messagingSenderId: '725686010307',
    projectId: 'satoshi-airline',
    storageBucket: 'satoshi-airline.appspot.com',
    iosClientId: '725686010307-hp603n4uhisamcerf20h4ps97qumg8b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.satoshi.RunnerTests',
  );
}
